name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish to Cloudflare
        run: wrangler deploy
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CF_API_EMAIL: ${{ secrets.CF_API_EMAIL }}
